create table flows
(
    id        bigint generated by default as identity
        primary key,
    srcaddr   integer,
    dstaddr   integer,
    input     integer,
    output    integer,
    dpkts     integer,
    doctets   integer,
    srcport   smallint,
    dstport   smallint,
    tcp_flags char,
    prot      char,
    tos       char,
    src_as    smallint,
    dst_as    smallint,
    src_mask  char,
    dst_mask  char,
    exporter  integer,
    first     integer,
    last      integer
);

alter table flows
    owner to supabase_admin;

grant select, update, usage on sequence flows_id_seq to postgres;

grant select, update, usage on sequence flows_id_seq to anon;

grant select, update, usage on sequence flows_id_seq to authenticated;

grant select, update, usage on sequence flows_id_seq to service_role;

create
policy "Enable read access for all users" on flows
    as permissive
    for
select
    using true;

grant
delete
, insert, references, select, trigger, truncate, update on flows to postgres;

grant delete
, insert, references, select, trigger, truncate, update on flows to anon;

grant delete
, insert, references, select, trigger, truncate, update on flows to authenticated;

grant delete
, insert, references, select, trigger, truncate, update on flows to service_role;

create table exporters
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp with time zone default now() not null,
    ip                integer,
    snmp_version      smallint,
    snmp_community    varchar,
    snmpv3_username   varchar,
    snmpv3_level      smallint,
    snmpv3_auth_proto varchar,
    snmpv3_auth_pass  varchar,
    snmpv3_priv_proto varchar,
    snmpv3_priv_pass  varchar
);

alter table exporters
    owner to supabase_admin;

grant select, update, usage on sequence exporters_id_seq to postgres;

grant select, update, usage on sequence exporters_id_seq to anon;

grant select, update, usage on sequence exporters_id_seq to authenticated;

grant select, update, usage on sequence exporters_id_seq to service_role;

grant
delete
, insert, references, select, trigger, truncate, update on exporters to postgres;

grant delete
, insert, references, select, trigger, truncate, update on exporters to anon;

grant delete
, insert, references, select, trigger, truncate, update on exporters to authenticated;

grant delete
, insert, references, select, trigger, truncate, update on exporters to service_role;

create table interfaces
(
    id          bigint generated by default as identity
        constraint interface_pkey
            primary key,
    created_at  timestamp with time zone default now() not null,
    exporter    bigint,
    snmp_index  bigint,
    description varchar,
    alias       varchar,
    speed       varchar,
    enabled     boolean
);

alter table interfaces
    owner to supabase_admin;

grant
delete
, insert, references, select, trigger, truncate, update on interfaces to postgres;

grant delete
, insert, references, select, trigger, truncate, update on interfaces to anon;

grant delete
, insert, references, select, trigger, truncate, update on interfaces to authenticated;

grant delete
, insert, references, select, trigger, truncate, update on interfaces to service_role;

create table services
(
    id   bigint generated by default as identity
        primary key,
    addr integer,
    port smallint,
    name varchar
);

alter table services
    owner to supabase_admin;

grant select, update, usage on sequence services_id_seq to postgres;

grant select, update, usage on sequence services_id_seq to anon;

grant select, update, usage on sequence services_id_seq to authenticated;

grant select, update, usage on sequence services_id_seq to service_role;

grant
delete
, insert, references, select, trigger, truncate, update on services to postgres;

grant delete
, insert, references, select, trigger, truncate, update on services to anon;

grant delete
, insert, references, select, trigger, truncate, update on services to authenticated;

grant delete
, insert, references, select, trigger, truncate, update on services to service_role;

create table config
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp with time zone default now() not null,
    snmp_config json
);

alter table config
    owner to supabase_admin;

grant select, update, usage on sequence config_id_seq to postgres;

grant select, update, usage on sequence config_id_seq to anon;

grant select, update, usage on sequence config_id_seq to authenticated;

grant select, update, usage on sequence config_id_seq to service_role;

grant
delete
, insert, references, select, trigger, truncate, update on config to postgres;

grant delete
, insert, references, select, trigger, truncate, update on config to anon;

grant delete
, insert, references, select, trigger, truncate, update on config to authenticated;

grant delete
, insert, references, select, trigger, truncate, update on config to service_role;

