#!/bin/bash
set -e

# Resolve project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"

# Detect Conan
if command -v conan &> /dev/null; then
    CONAN_CMD="conan"
elif [ -f "$PROJECT_ROOT/.venv/bin/conan" ]; then
    CONAN_CMD="$PROJECT_ROOT/.venv/bin/conan"
else
    echo "ERROR: 'conan' command not found."
    exit 1
fi

BUILD_DIR="${PROJECT_ROOT}/cmake-build-windows-release"

# Clean previous build
if [ -d "$BUILD_DIR" ]; then
    rm -rf "$BUILD_DIR"
fi
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"

echo "========================================"
echo "Installing Dependencies for Windows..."
echo "========================================"

# Install dependencies using the Windows profile
# We use the main conanfile.txt for now unless we find Windows-specific issues
"$CONAN_CMD" install "$PROJECT_ROOT" \
    --output-folder=. \
    --build=missing \
    -pr:h "$PROJECT_ROOT/profiles/windows" \
    -pr:b default \
    -s build_type=Release \
    -c "tools.build:cflags=['-std=gnu11']"

echo "========================================"
echo "Configuring CMake for Windows..."
echo "========================================"

# Configure CMake
# We must point to the toolchain file generated by Conan
# and specify the toolchain for cross-compilation if Conan doesn't fully handle it via the toolchain file alone (contracts vary).
# Usually conan_toolchain.cmake handles the compiler setup if [conf] tools.build:compiler_executables is set in profile.
cmake "$PROJECT_ROOT" \
      -DCMAKE_TOOLCHAIN_FILE="build/Release/generators/conan_toolchain.cmake" \
      -DCMAKE_BUILD_TYPE=Release \
      -DUSE_REDIS=ON \
      -DENABLE_LOGGING=ON \
      -DUSE_ARENA=ON \
      -DBUILD_STATIC=ON 

echo "========================================"
echo "Building..."
echo "========================================"

cmake --build . -j$(nproc)

echo ""
echo "SUCCESS: Windows build completed."
if [ -f "cnetflow.exe" ]; then
    echo "Binary: $BUILD_DIR/cnetflow.exe"
fi
