services:
  cnetflow:
    build:
      context: .
    image: cnetflow
    #restart: no
    restart: unless-stopped
    ports:
      - "2055:2055/udp"
    environment:
      - UV_THREADPOOL_SIZE
      - CH_CONN_STRING
      - TZ
  softflowd:
    image: kagurazakanyaa/softflowd
    command: [ "softflowd",  "-v","9","-i", "any" ,"-D", "-t","maxlife=60s" ,"-P" ,"udp" ,"-n", $SOFTFLOWD_DST ]
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3001:3000/tcp
    environment:
      - CH_CONN_STRING
      - TZ
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/etc_dashboards/:/etc/grafana/json_dashboards/
