# Dockerfile for building cnetflow RPM on RHEL7/CentOS7
FROM centos:7
RUN mkdir -p /etc/yum.repos.d/old
RUN mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/old/
ADD centos-base.repo /etc/yum.repos.d/
ADD epel.repo /etc/yum.repos.d/
ADD centos-scl.repo /etc/yum.repos.d/
# Install EPEL repository for cmake3
RUN yum install -y epel-release

# Install build dependencies with newer GCC from SCL
RUN yum install -y \
    cmake3 \
    devtoolset-7-gcc \
    devtoolset-7-gcc-c++ \
    make \
    rpm-build \
    postgresql-devel \
    libuv-devel \
    hiredis-devel \
    perl-core \
    flex \
    bison \
    rh-git227 \
    rh-python38 \
    wget \
    && yum clean all

# Install Conan 2 binary
RUN wget https://github.com/conan-io/conan/releases/download/2.31.1/conan-2.31.1-linux-x86_64.tgz && \
    tar -xzf conan-2.31.1-linux-x86_64.tgz -C /usr/local && \
    rm conan-2.31.1-linux-x86_64.tgz && \
    ln -s /usr/bin/cmake3 /usr/local/bin/cmake

# Set working directory
WORKDIR /build

# Copy source code
COPY . .

# Package version passed from GitHub Actions as --build-arg PKG_VERSION
ARG PKG_VERSION=1.0.0

# Create build directory and configure with SCL GCC, Git, and Python 3.8
# Use devtoolset-7 which provides GCC 7.3.1 with C11 support
RUN scl enable devtoolset-7 rh-git227 rh-python38 "bash -lc 'set -ex && export CC=/opt/rh/devtoolset-7/root/usr/bin/gcc && export CXX=/opt/rh/devtoolset-7/root/usr/bin/g++ && export LEX=/usr/bin/flex && export YACC=\"/usr/bin/bison -y\" && export M4=/usr/bin/m4 && conan profile detect --force && conan install . --build=* --build=!gnu-config* -s build_type=Release -c \"tools.build:cflags=[\\\"-std=gnu11\\\"]\" && mkdir -p build && cd build && cmake3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../build/Release/generators/conan_toolchain.cmake -DBUILD_FOR_RHEL7=ON -DCPACK_PACKAGE_VERSION=${PKG_VERSION} .. && cmake3 --build . && cpack3 -G RPM'"

# The RPM will be in /build/build/
# To extract it, run:
# docker build -f Dockerfile.rhel7 -t cnetflow-rhel7-builder .
# docker create --name temp cnetflow-rhel7-builder
# docker cp temp:/build/build/cnetflow-1.0.0-1.el7.x86_64.rpm .
# docker rm temp
