services:
  cnetflow:
    build:
      context: .
    image: cnetflow
    ports:
      - "2055:2055/udp"
    environment:
      - UV_THREADPOOL_SIZE
      - PG_CONN_STRING
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./scripts/sql/psql/:/docker-entrypoint-initdb.d/:r
    ports:
      - "$POSTGRES_PORT:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  softflowd:
    image: kagurazakanyaa/softflowd
    command: [ "softflowd",  "-v","9","-i", "any" ,"-D", "-t","maxlife=10s" ,"-P" ,"udp" ,"-n", $SOFTFLOWD_DST ]
    network_mode: host

  grafana:
    image: grafana/grafana
    ports:
      - 3001:3000/tcp
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/etc_dashboards/:/etc/grafana/json_dashboards/
