services:
  cnetflow:
    build:
      context: .
    image: cnetflow
    restart: unless-stopped
    ports:
      - "2055:2055/udp"
    environment:
      - UV_THREADPOOL_SIZE
      - PG_CONN_STRING
    depends_on:
      - db
  dbrest:
    image: postgrest/postgrest
    environment:
      - PGRST_DB_URI=${PG_CONN_STRING}
      - PGRST_DB_ANON_ROLE
      - PGRST_DB_AGGREGATES_ENABLED
      - TZ
    ports:
      - "3003:3000"
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: postgres
    #image: postgres
    #image: codercms/postgres-uint128:15-1.0.0
    build:
      context: ./timescale_pg_cron/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - TZ
    volumes:
      - ./data/psql:/var/lib/postgresql/data
      - ./scripts/sql/psql/:/docker-entrypoint-initdb.d/:r
    ports:
      - "$POSTGRES_PORT:5432"
    restart: unless-stopped
    #    command:
    #      [
    #        "postgres",
    #        "-c",
    #        "log_statement=all",
    #        "-c",
    #        "log_destination=stderr",
    #        "-c",
    #        "shared_preload_libraries=pg_cron",
    #        "-c",
    #        "cron.database_name=${POSTGRES_DB-postgres}",
    #      ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  softflowd:
    image: kagurazakanyaa/softflowd
    command: [ "softflowd",  "-v","9","-i", "any" ,"-D", "-t","maxlife=10s" ,"-P" ,"udp" ,"-n", $SOFTFLOWD_DST ]
    network_mode: host
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3001:3000/tcp
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/etc_dashboards/:/etc/grafana/json_dashboards/
