services:
  cnetflow:
    build:
      context: .
    image: cnetflow
    ports:
      - "2055:2055/udp"
    environment:
      - UV_THREADPOOL_SIZE
      - PG_CONN_STRING
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: bank
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  db:

networks:
  db:
    driver: bridge