create table flows_v5
(
    id        bigint generated by default as identity
        primary key,
    srcaddr   integer,
    dstaddr   integer,
    input     integer,
    output    integer,
    dpkts     integer,
    doctets   integer,
    srcport   smallint,
    dstport   smallint,
    tcp_flags char,
    prot      char,
    tos       char,
    src_as    smallint,
    dst_as    smallint,
    src_mask  char,
    dst_mask  char,
    exporter  integer,
    first     integer,
    last      integer
);
create table flows_v9
(
    id        bigint generated by default as identity
        primary key,
    srcaddr   integer,
    dstaddr   integer,
    input     integer,
    output    integer,
    dpkts     bigint,
    doctets   bigint,
    srcport   smallint,
    dstport   smallint,
    tcp_flags char,
    prot      char,
    tos       char,
    src_as    smallint,
    dst_as    smallint,
    src_mask  char,
    dst_mask  char,
    exporter  integer,
    first     integer,
    last      integer
);
create table exporters
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp with time zone default now() not null,
    ip                integer,
    snmp_version      smallint,
    snmp_community    varchar,
    snmpv3_username   varchar,
    snmpv3_level      smallint,
    snmpv3_auth_proto varchar,
    snmpv3_auth_pass  varchar,
    snmpv3_priv_proto varchar,
    snmpv3_priv_pass  varchar
);

create table interfaces
(
    id          bigint generated by default as identity
        constraint interface_pkey
            primary key,
    created_at  timestamp with time zone default now() not null,
    exporter    bigint,
    snmp_index  bigint,
    description varchar,
    alias       varchar,
    speed       varchar,
    enabled     boolean
);

create table services
(
    id   bigint generated by default as identity
        primary key,
    addr integer,
    port smallint,
    name varchar
);

create table config
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp with time zone default now() not null,
    snmp_config json
);
