{
 "title": "cnetflow - time_bucket",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Exporter",
    "label": "Exporter",
    "query": "select distinct(exporter) from flows where first > now() - interval '7 day' group by exporter ;"
   },
   {
    "name": "Interface",
    "label": "Interface",
    "query": "select interface from (select input as interface from flows where first > now() - interval '7 day' AND exporter = '$Exporter' group by input UNION select output as interface from flows where first > now() - interval '7 day'  AND exporter = '$Exporter' group by output) group by interface;"
   },
   { "name": "N", "label": "N", "query": "20" }
  ]
 },
 "panels": [
  {
   "title": "Input",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "cnetflow",
     "rawSql": "SELECT time_bucket('$__interval'::interval, bucket::TIMESTAMP AT TIME ZONE 'UTC' AT TIME ZONE 'GMT-3') AS time ,\n       sum(total_bytes) as input_octets\nFROM flows_hourly\nWHERE 1=1\nAND exporter = '$Exporter'\nAND input =  $Interface \nAND $__timeFilter(bucket + INTERVAL '3 HOUR')\nGROUP BY time\nORDER BY time DESC ;"
    },
    {
     "dataset": "cnetflow",
     "rawSql": "SELECT time_bucket('$__interval'::interval, bucket::TIMESTAMP AT TIME ZONE 'UTC' AT TIME ZONE 'GMT-3') AS time ,\n       sum(total_bytes) as output_octets\nFROM flows_hourly \nWHERE 1=1\nAND exporter = '$Exporter'\nAND output = $Interface \nAND $__timeFilter(bucket + INTERVAL '3 HOUR')\nGROUP BY time\nORDER BY time DESC ;"
    }
   ]
  },
  {
   "title": "Input",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cnetflow",
     "rawSql": "SELECT sum(doctets) as octets,\n       srcaddr,\n       dstaddr\nFROM flows\nWHERE 1=1\nAND exporter = '$Exporter'\nAND input = $Interface \nAND $__timeFilter(first + INTERVAL '3 HOUR')\nGROUP BY srcaddr,dstaddr\nORDER by octets DESC\n\nlimit $N;"
    },
    {
     "dataset": "cnetflow",
     "rawSql": "SELECT sum(doctets) as octets,\n       srcaddr,\n       dstaddr\nFROM flows\nWHERE 1=1\nAND exporter = '$Exporter'\nAND output = $Interface \nAND $__timeFilter(first + INTERVAL '3 HOUR')\nGROUP BY srcaddr,dstaddr\nORDER by octets DESC\nlimit $N;"
    }
   ]
  },
  {
   "title": "Top Port Protocol",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "cnetflow",
     "rawSql": "SELECT sum(total_bytes) as octets_in,\n       dstport as dstport,\n       prot as protocol\nFROM flows_hourly\nWHERE 1=1\nAND exporter = '$Exporter'\nAND input = $Interface \nAND $__timeFilter(bucket + INTERVAL '3 HOUR')\nGROUP BY dstport,protocol\nORDER BY octets_in DESC \nLIMIT $N;"
    },
    {
     "dataset": "cnetflow",
     "rawSql": "SELECT sum(total_bytes) as octets_out,\n       dstport as dstport,\n       prot as protocol\nFROM flows_hourly\nWHERE 1=1\nAND exporter = '$Exporter'\nAND output = $Interface \nAND $__timeFilter(bucket + INTERVAL '3 HOUR')\nGROUP BY dstport,protocol\nORDER BY octets_out DESC \nLIMIT $N;"
    }
   ]
  },
  {
   "title": "Output - Top SrcAddr",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "cnetflow",
     "rawSql": "\nSELECT sum(total_bytes) as octets_in,\n       srcaddr as src_addr\nFROM flows_hourly \nWHERE 1=1\nAND exporter = '$Exporter'\nAND input = $Interface \nAND $__timeFilter(bucket + INTERVAL '3 HOUR')\nGROUP BY srcaddr\norder by octets_in desc\n"
    },
    {
     "dataset": "cnetflow",
     "rawSql": "\nSELECT sum(total_bytes) as octets_out,\n       srcaddr as src_addr\nFROM flows_hourly\nWHERE 1=1\nAND exporter = '$Exporter'\nAND output = $Interface \nAND $__timeFilter(bucket + INTERVAL '3 HOUR')\nGROUP BY src_addr\norder by octets_out desc"
    },
    {
     "dataset": "cnetflow",
     "rawSql": "\nSELECT sum(total_bytes) as octets_in,\n       dstaddr as dst_addr\nFROM flows_hourly \nWHERE 1=1\nAND exporter = '$Exporter'\nAND input = $Interface \nAND $__timeFilter(bucket + INTERVAL '3 HOUR')\nGROUP BY dstaddr\norder by octets_in desc"
    },
    {
     "dataset": "cnetflow",
     "rawSql": "\nSELECT sum(total_bytes) as octets_out,\n       dstaddr as dst_addr\nFROM flows_hourly\nWHERE 1=1\nAND exporter = '$Exporter'\nAND output = $Interface \nAND $__timeFilter(bucket + INTERVAL '3 HOUR')\nGROUP BY dstaddr\norder by octets_out desc"
    }
   ]
  }
 ]
}